# Generated by Django 2.2.7 on 2019-12-10 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='菜的编号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='菜名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('img', models.ImageField(default='default/cuisineph.png', upload_to='menus', verbose_name='图片')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='CuisineKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, unique=True, verbose_name='菜式')),
                ('num', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('desk_id', models.AutoField(primary_key=True, serialize=False, verbose_name='桌号')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='登录名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='消费总额')),
                ('desk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Desk', verbose_name='桌号')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='数量')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Cuisine', to_field='name', verbose_name='菜名')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Order', verbose_name='订单号')),
            ],
        ),
        migrations.AddField(
            model_name='cuisine',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.CuisineKind', to_field='kind', verbose_name='菜式'),
        ),
    ]
