# Generated by Django 2.2.7 on 2019-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='intro',
            field=models.TextField(default='暂无介绍', verbose_name='介绍'),
        ),
    ]
