# Generated by Django 2.2.7 on 2019-12-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20191214_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom_num',
            new_name='customer_num',
        ),
    ]
