# Generated by Django 2.2.7 on 2019-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20191214_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
    ]
