# Generated by Django 2.2.7 on 2019-12-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20191215_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='tel',
            field=models.CharField(default='未知', max_length=11, verbose_name='手机号码'),
        ),
    ]
