# Generated by Django 2.2.7 on 2019-12-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='img',
            field=models.ImageField(default='media/default/cuisineph.png', upload_to='menus', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.CuisineKind', verbose_name='菜式'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='菜名'),
        ),
        migrations.AlterField(
            model_name='cuisinekind',
            name='kind',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='菜式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Desk', verbose_name='桌号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Cuisine', verbose_name='菜名'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Order', verbose_name='订单号'),
        ),
    ]
